



define bg_list = [
    "bg_community_5",
    "bg_amusement_park_1",
    "bg_kitchen_1",
    "bg_kitchen_2",
    "bg_living_room_1",
    "bg_bedroom_3",
    "bg_bedroom_4",
    "bg_living_room_2",
    "bg_shop_1",
    "bg_office_1",
    "bg_living_room_3",
    "bg_community_2",
    "bg_bedroom_1",
    "bg_shop_2",
    "bg_sky_1",
    "bg_bedroom_2",
    "bg_living_room_4",
    "bg_sky_4",
    "bg_sky_5",
    "bg_sky_2",
    "bg_sky_3",
    "bg_office_4",
    "bg_community_1",
    "bg_office_5",
    "bg_shop_4",
    "bg_community_4",
    "bg_sky_10",
    "bg_subway_2",
    "bg_shop_7",
    "bg_sky_7",
    "bg_sky_8",
    "bg_sky_9",
    "bg_subway_1",
    "bg_shop_6",
    "bg_park_3",
    "bg_park_4",
    "bg_street_1",
    "bg_street_2",
    "bg_street_4",
]
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
